### ISSUE TITLE
i3-gnome session crashes

### ISSUE THREAD

**Issue by vredesbyyrd** [51v4n/i3-gnome#14]
I just started using i3-gnome on an arch install with gnome 3.26.2. From gdm, an i3 session starts no problem. But an i3-gnome session crashes. It appears to load correctly for about a second, then the desktop goes black and the status bar at the bottom gets cut in half horizontally. Interestingly, the only mod key that works is for rofi, which will open, but cannot successfully launch anything from rofi. Only way out is by powering off. 

I would like to troubleshoot, but i dont know what logs i should be looking at.  Any tips where to start would be very appreciated.

**Comment by 51v4n** [comment]
That behavior you mention it's weird. But let's see:
		
- What's on your `.xinitrc`?
Make sure it has `exec i3`

This is my first approach.
To be honest, i need more information about to figure out what's going on.

**Comment by vredesbyyrd** [comment]
'exec i3' is in the xinitrc. 

I am very new to i3. Been using gnome for years but have always had some qualms with aspects of its window handling. I have been intending to try a manual gnome / i3 setup for awhile now, but i just kinda jumped into it tonight without doing much reading first when i stumbled upon your package. 

I suppose i may just have to do a some reading on i3 and see if i can find any relevant logs to point me in the right direction. I definitely want to figure it out though because your package looks to take care of all the backend dirty work that has been putting me off to trying a setup like this until now.

**Comment by 51v4n** [comment]
> I am very new to i3. Been using gnome for years but have always had some qualms with aspects of its window handling. I have been intending to try a manual gnome / i3 setup for awhile now, but i just kinda jumped into it tonight without doing much reading first when i stumbled upon your package. 

No problem, the key parts of window managers are:
1) config files: your first way to customization/personalization.
2) almost all the navigation works thanks by keystrokes.

Just take your time to get along with the environment. It's not that hard.

>I suppose i may just have to do a some reading on i3 and see if i can find any relevant logs to point me in the right direction. 

Yup, this is a must, just to understand how it works and how can be customized. 

>I definitely want to figure it out though because your package looks to take care of all the backend dirty work that has been putting me off to trying a setup like this until now.

I agree, specially if we take a look at issue #11, i'm struggling with it because we are talking about a very specific situation (but it will be fixed anyway).

--
Another thing that i'm thinking:

what are your system specs? (xorg?, wayland?) 

Most of the users of i3wm change to [i3-gaps](https://github.com/Airblader/i3) because it has more features, you'll probably want to give a try. If you're an arch user you'll find i3-gaps on the AUR.

--
I suggest you to take a look to all closed issues, it can help you to understand more about this combination of GNOME + i3 (just for documentation).

--
Following your EDIT: that's probably the reason that i3-gnome isn't get up and running, i3-gnome loads a lot of GNOME's components, if you mention that you have a minimal setup some components are missinng, consider that too.

**Comment by vredesbyyrd** [comment]
Thanks for all the info. 

> Another thing that i'm thinking:
>
>what are your system specs? (xorg?, wayland?)
>
>Most of the users of i3wm change to i3-gaps because it has more features, you'll probably want to >give a try. If you're an arch user you'll find i3-gaps on the Aur. 

I use arch and xorg, on an intel based laptop. I rely too much on a few things that wayland/xwayland just doesnt seem to handle well enough yet. Last time i seriously tried out wayland was a few months ago. For i3-gnome, I am using i3-gaps (from the aur) instead of i3wm. From the small amount of research i have done so far, my thinking was i3-gaps looked to be more feature full, and I have vision issues where gaps in the windows are a must because they help distinguish between windows. Really, my current gnome setup on my daily driver is as close to looking and acting like a tiling window manager you can get without actually being a tiling wm. That just progressed naturally over the years trying to develop something that would work best for my eye issues. Essentially, i cant have anything loud or distracting in my peripheral. So my entire UI has no icons and is fully text based. The next logical step was using a tiling WM. 

>I suggest you to take a look to all closed issues, it can help you to understand more about this >combination of GNOME + i3 (just for documentation).

Thats the first thing i did actually. I try to do that when trying out anything new.. 

>Following your EDIT: that's probably the reason that i3-gnome isn't get up and running, i3-gnome >loads a lot of GNOME's components, if you mention that you have a minimal setup some >components are missinng, consider that too. 

 I should have said 'stock' setup instead of 'minimal'. I installed full 'gnome desktop' and most of 'gnome-extras'...essentially a vanilla gnome de. All the components are there. I just meant that i did not customize it a ton and run the risk of breaking something. So i cant see the issues I am experiencing being the result of my gnome install. 

Thanks again for all the info, ill do some more tinkering/reading when time abides and see where it leads me.

**Comment by 51v4n** [comment]
>I should have said 'stock' setup instead of 'minimal'. I installed full 'gnome desktop' and most of 'gnome-extras'...essentially a vanilla gnome de. All the components are there. I just meant that i did not customize it a ton and run the risk of breaking something. So i cant see the issues I am experiencing being the result of my gnome install.

Oh.

>Thanks again for all the info, ill do some more tinkering/reading when time abides and see where it leads me.

No problem. 

FWIW you can check what's going wrong with the command:
`journalctl -u gdm`

wich will display more useful info about the issue.

**Comment by 51v4n** [comment]
i know what's going on.
the latest version of `xorg-server`, `xorg-server-common`, `xorg-server-xwayland` (1.19.6+13+gd0d1a694f-1) all of them on the `[testing]` repository.
It causes the crash, i know it because i've had the same issue like you moments ago, just downgraded to 1.19.6-2.

`sudo pacman -Syu "xorg-server<=1.19.6-2" "xorg-server-common<=1.19.6-2" "xorg-server-xwayland<=1.19.6-2"`

in case you have something similar, of course.

**Comment by vredesbyyrd** [comment]
Im on xorg 1.19.6.2  already.  

I have not had time to troubleshoot it today, and probably wont for a couple days unfortunately. The little i did play with it this morning, i wasnt able to get any usable logs. I have to hard power down.

Its probably something on my end, so dont sweat it. I have not tried it without rofi or tilda installed yet.  So when I can I am going to try it without any programs installed other than i3 and gnome. Ill post my results asap. Thanks again.

**Comment by vredesbyyrd** [comment]
Did some troubleshooting this morning. I uninstalled 'rofi' and 'tilda' terminal. That did not change anything. Next, I restored an identical disk image of my gnome/arch install. Then installed i3-gnome. Now have a working i3-gnome session. Next, installed rofi and tilda terminal. That did not break session and everything is still working. 

I am still not sure what precisely was causing this crash, since both installs were essentially identical. But now that things seem to be in working order, i am closing this 'issue'.

**Comment by 51v4n** [comment]
It's cool that you have everything ready and works.
Cheers!

**Comment by NullVoxPopuli** [comment]
I think this may have resurfaced on 18.04

**Comment by 51v4n** [comment]
Please, could you print the version of GNOME that you're using?

**Comment by 51v4n** [comment]
We're not talking about OS but for sure about DE.

**Comment by NullVoxPopuli** [comment]
I think I realized that the color I see upon login is the same one used for the background for the unlock screen (after gdm slides up the picture, you type in your password, and the form fades)

**Comment by NullVoxPopuli** [comment]
>  you should consider that you don't have a vanilla version of GNOME.

how can you tell?

**Comment by NullVoxPopuli** [comment]
actually, "Gnome Classic" has the same issue. So it's clearly an issue with Gnome on my computer. Will investigate and report back.

**Comment by NullVoxPopuli** [comment]
fixed it.

all I had to do was:

```bash
sudo apt install --reinstall gnome-session ubuntu-desktop gdm3
```
proof of gdm:

```bash
 $ echo $DESKTOP_SESSION
i3-gnome

$ ps -ef | grep '/[X]'
gdm       2797  2484  0 11:59 tty1     00:00:00 /usr/bin/Xwayland :1024 -rootless -terminate -accessx -core -listen 4 -listen 5 -displayfd 6
lpresto+  3258  3256  2 12:00 tty2     00:00:04 /usr/lib/xorg/Xorg vt2 -displayfd 3 -auth /run/user/1000/gdm/Xauthority -background none -noreset -keeptty -verbose 3
```

**Comment by 51v4n** [comment]
@NullVoxPopuli 
> how can you tell?

Sorry for the misconception, i just wanted to say that GNOME and ubuntu's GNOME it's not identical, so, as you can look over the closed issues a minor change regarding `gnome-session` or `xsettings` or even an update from GNOME breaks this tweak. So you have to look if all of the successful cases of use are on the same way to you.

> actually, "Gnome Classic" has the same issue. So it's clearly an issue with Gnome on my computer. Will investigate and report back.

How can you tell?
The last [update](https://github.com/51v4n/i3-gnome/releases/tag/3.28.1) focus exactly on this.

**Comment by NullVoxPopuli** [comment]
> How can you tell?
> The last update focus exactly on this.

I read that "Gnome Classic" is vanilla gnome, so when that didn't work by itself, I figured the problem _couldn't_ be with i3-gnome.
I think re-installing those packages (gnome-session ubuntu-desktop gdm3), fixed something - so it confirms that something was messed up on my machine.
