### ISSUE TITLE
Log-in keeps restarting

### ISSUE THREAD

**Issue by Strafos** [51v4n/i3-gnome#15]
I have a standard Ubuntu 16.04 install and i3. When I try to log in with i3-gnome, the screen will go black, and then I'm back at the log in screen.

**Comment by 51v4n** [comment]
>I have a standard Ubuntu 16.04 install and i3.

i keep in mind that you have Unity instead of GNOME.
You should use GNOME to successfully use this tweak, Unity has it's own way to get the things work, so that's why you have the issue.

**Comment by grant-park** [comment]
I also have this issue; using Ubuntu-GNOME. `gnome-shell --version` prints `3.20.4`

**Comment by 51v4n** [comment]
> I also have this issue; using Ubuntu-GNOME. gnome-shell --version prints 3.20.4

You should install the latest version of GNOME (3.26.2) because the are a lot of changes including session infrastructure [must read](https://bugs.archlinux.org/task/53800).

**Comment by grant-park** [comment]
Got it, thanks. Updated to Ubuntu-GNOME 17.04 with gnome-shell version 3.26.2 and it's working now.

**Comment by 51v4n** [comment]
No problem! enjoy.

**Comment by workcomplete** [comment]
Having this same issue on Arch. gnome-shell --version 40.1

**Comment by muktupavels** [comment]
Please don't comment on old closed issue! It is unlikely that you have same underlying issue.

You will need to find error why you are logged out. After failed login login in working session and check `journalctl` to see if there is some errors. You could also add `--debug` to this line - https://github.com/i3-gnome/i3-gnome/blob/main/session/gnome-session-i3#L9 to get more debug output.
