### ISSUE TITLE
Debian Buster: xsession cannot launch command with args

### ISSUE THREAD

**Issue by mist** [51v4n/i3-gnome#16]
On my system gdm-x-session fails to launch `gnome-session --session=i3-gnome`:

```
Feb 23 09:16:46 nike /usr/lib/gdm3/gdm-x-session[3582]: Xsession: unable to launch "gnome-session --session=i3-gnome" X session ---
Feb 23 09:16:46 nike /usr/lib/gdm3/gdm-x-session[3582]: "gnome-session --session=i3-gnome" not found; falling back to default session.
```

I looked into the gnome-classic-session and found out that they use a helper script, so I copied it and changed it a little:

```
.-(~)-------------------------------------------------------------------------(mist@nike)-
`--> cat =gnome-session-classic
#! /bin/sh
env GNOME_SHELL_SESSION_MODE=classic gnome-session --session gnome-classic "$@"
.-(~)-------------------------------------------------------------------------(mist@nike)-
`--> cat =gnome-session-i3
#! /bin/sh
env GNOME_SHELL_SESSION_MODE=classic gnome-session --session i3-gnome "$@"
```
and put that helper script into the xsession-file. Now it is starting.
My gnome-settings don't have everything the have in Gnome - but it is usable which it wasn't when using the old method with starting `gnome-settings-daemon` from withing `i3`.

More information:
Debian testing (buster)
gnome-session: 3.26.1-2
gnome: 1:3.22+8
gnome-shell: 3.26.2-4

I can file a PR for this fix if you want to add it.

**Comment by 51v4n** [comment]
Hi,
>I can file a PR for this fix if you want to add it.

Please, i would like to see, i'll take time on this.

**Comment by 51v4n** [comment]
Looks like you implemented your approach.
Closing.

**Comment by mist** [comment]
I didn't come to test if I missed something in the commit because I made the changes locally first. That's why there is no PR yet.

**Comment by 51v4n** [comment]
Oh, my apologies, i just misunderstood the course of this issue. Sorry for a late answer since the beginning.
Re-opening

**Comment by Khady** [comment]
Using debian stable here (9, gnome 3.22) and I get the same error. I didn't manage to setup the `gnome-session-i3` properly to fix the problem tho. Interested to know how to fix that.

**Comment by 51v4n** [comment]
@Khady ,
i highly recommend you to update GNOME to the latest version (3.28.0) because there are a lot of changes, especially regarding the GNOME session infrastructure, actually, every update of GNOME breaks this (`i3-gnome`) tweak, that's the reason why you can't get it work. 

Once you updated GNOME you can install i3-gnome with `make`, if you still have the issue, you can try @mist 's approach.

Cheers

**Comment by 51v4n** [comment]
I screwed the following of the issue with @mist didn't get an answer after re-opening this issue, don't know if his approach still works with the latest version of GNOME. You should consider that as well.

P.D: sorry @mist

**Comment by mist** [comment]
So, sorry for my late reply. After updating gnome my approach didn't work again, so I merged current head and it worked.
Still have to figure out if my approach is needed at all now.

**Comment by mist** [comment]
So, sorry for my late reply. After updating gnome my approach didn't work again, so I merged current head and it worked.
Created PR for it.

**Comment by 51v4n** [comment]
@mist no problem! i'll take a look at your PR.
