### ISSUE TITLE
i3-gnome with gnome 3.28

### ISSUE THREAD

**Issue by jas01** [51v4n/i3-gnome#17]
It's seem with the lates update i3-gnome stop working. 
I cannot say it's not because of me, but I'm using i3-gnome since 1 year without any issue. After last upgrade with gnome 3.28 the i3-gnome session just don't open. And because of my lack of knowledge with gnome I don't event know where to find the log so no idea of the error message but after login I'm instantly go back to gdm.

**Comment by killajoe** [comment]
same here, also try to us elightdm with the same result, and nor related log to find only what i already post here:
https://github.com/mephux/i3-gnome/issues/4

**Comment by 51v4n** [comment]
I have the same problem here as well, but i can't get even get GNOME work, the experience tell us that every update there's something new about `gnome-session` or related to the `gnome-session-daemon` one little modification to the components that are required to get i3 into GNOME.

I'll figure out what's going on that's for sure.

Any help is welcome.

Thanks for let us know!

**Comment by jas01** [comment]
Le 25/03/2018 à 14:04:23+0000, Jesús Castro a écrit
> I have the same problem here as well, but i can't get even get GNOME work, the
> experience tell us that every update there's something new about gnome-session
> or related to the gnome-session-daemon one little modification to the
> components that are required to get i3 into GNOME.
>
> I'll figure out what's going on that's for sure.
>
> Any help is welcome.

Don't if it's the right solution but with


# -*- mode: conf -*-

[GNOME Session]
Name=i3-gnome
RequiredComponents=org.gnome.SettingsDaemon.A11ySettings;org.gnome.SettingsDaemon.Clipboard;org.gnome.SettingsDaemon.Color;org.gnome.SettingsDaemon.Datetime;org.gnome.SettingsDaemon.Housekeeping;org.gnome.SettingsDaemon.Keyboard;org.gnome.SettingsDaemon.MediaKeys;org.gnome.SettingsDaemon.Mouse;org.gnome.SettingsDaemon.Power;org.gnome.SettingsDaemon.PrintNotifications;org.gnome.SettingsDaemon.Rfkill;org.gnome.SettingsDaemon.ScreensaverProxy;org.gnome.SettingsDaemon.Sharing;org.gnome.SettingsDaemon.Smartcard;org.gnome.SettingsDaemon.Sound;org.gnome.SettingsDaemon.Wacom;org.gnome.SettingsDaemon.XSettings;i3-gnome


inside

  /usr/share/gnome-session/sessions/i3-gnome.session

it's working.

I still find out some change in the behavior (especially with font size),
but at least I got my session...

Regards

**Comment by 51v4n** [comment]
@jas01 

> it's working.

¯\_(ツ)_/¯

Let's give a try then.

**Comment by 51v4n** [comment]
@jas01 Can confirm, your approach fixes the session.
I'll update it with your tweak to fix it.

Cheers!

**Comment by 51v4n** [comment]
Just to make sound, with the update of `i3-gnome.session` GNOME control center it's not working, that bring us to #11 but in general, i suggest to make changes under GNOME.

**Comment by 51v4n** [comment]
Considering this issue as fixed, closing.
