### ISSUE TITLE
How do I use it?

### ISSUE THREAD

**Issue by j4cobgarby** [51v4n/i3-gnome#19]
I have it installed, but how do I use it? It might sound like a silly question, but I can't work it out, and it doesn't say anywhere.

**Comment by NullVoxPopuli** [comment]
on the login screen, there should be a circle to the right of your name. Select `Gnome + i3` and login.

**Comment by 51v4n** [comment]
No worries, feel free to ask anything about i3-gnome.
As @NullVoxPopuli says, it's that quite simple, you just select from the login screen.

**Comment by 51v4n** [comment]
You can read this closed issue[1] to get started with this tweak (i3-gnome).

Cheers!

[1] #10

**Comment by j4cobgarby** [comment]
It worked, thanks! I _thought_ it was this simple, but I must've just missed the option in the dropdown.
