### ISSUE TITLE
i3-gnome/wiki/Tips-&-Tricks

### ISSUE THREAD

**Issue by killajoe** [51v4n/i3-gnome#22]
`exec --no-startup-id /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 `

is helping here too, on getting password checks aviable

**Comment by NullVoxPopuli** [comment]
what's that do?

**Comment by killajoe** [comment]
yes i do use apps launching from bar like pamac (packagemanager): [shot](https://i.imgur.com/HEQgTwT.png)

**Comment by 51v4n** [comment]
@killajoe cool, didn't know anything about that.
For sure this will be added to the wiki!

Cheers!

**Comment by 51v4n** [comment]
@killajoe already implemented, [here](https://github.com/51v4n/i3-gnome/wiki/Tips-&-Tricks/6cbdafb933d34fabcea5f9bd2da8d9a945246c37), if you wish you can let me know if something has to be changed or improved.

**Comment by NullVoxPopuli** [comment]
Is there a tip&trick to getting automatic monitor switching?

**Comment by killajoe** [comment]
https://www.freedesktop.org/wiki/Software/polkit/
I am on Archlinux based system so there is a package called polkit-gnome and at gnome there is also sources:
https://download.gnome.org/sources/polkit-gnome/
